# Traefik Middlewares manifest for Kubernetes. Configures various middlewares used by Traefik.

# ======================
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: media
spec:
  redirectScheme:
    scheme: https
    permanent: true
---

# ======================
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: media
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow" # Don't index in search engines
    sslRedirect: true
    stsSeconds: 31536000 # Enable HSTS (force HTTPS for 1 year)
    stsIncludeSubdomains: true
    stsPreload: true
---

# ======================
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dashboard-auth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-dashboard-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
type: Opaque
data:
  users: YWRtaW46JGFwcjEkNXg1L0UzNC8kZWswSmNDbkVXVDYySmhDMm92M3V0MAoK
# ======================
