# Slskd Ingress Route Manifest

# slskd HTTP (redirects to HTTPS)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: slskd-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`slskd.<YOUR_DOMAIN>.sslip.io`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: slskd
          port: 5030
    - match: Host(`slskd.<YOUR_PUBLIC_IP>.sslip.io`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: slskd
          port: 5030
---
# slskd HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: slskd-https
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`slskd.<YOUR_DOMAIN>.sslip.io`)
      kind: Rule
      middlewares:
        - name: security-headers
      services:
        - name: slskd
          port: 5030
    - match: Host(`slskd.<YOUR_PUBLIC_IP>.sslip.io`)
      kind: Rule
      middlewares:
        - name: security-headers
      services:
        - name: slskd
          port: 5030
  tls:
    certResolver: letsencrypt
