# AdGuard Deployment manifest for Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      # Set security context for the pod
      securityContext:
        fsGroup: 1000
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 3000
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            # Mount points for AdGuard Home data and configuration
            - name: adguard-data
              mountPath: /opt/adguardhome/work
            - name: adguard-config
              mountPath: /opt/adguardhome/config
          # Resource requests and limits
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          # Probes for health checks
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          # Probe to check if the application is ready to serve traffic
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-data-pvc
        - name: adguard-config
          persistentVolumeClaim:
            claimName: adguard-config-pvc
