# Navidrome Deployment manifest for Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      # Security context to run as non-root user
      securityContext:
        fsGroup: 1000
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          ports:
            - containerPort: 4533
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            # Mount config directory
            - name: media-storage
              mountPath: /config
              subPath: navidrome/config
            # Mount music library
            - name: media-storage
              mountPath: /music
            # Mount custom config file
            - name: navidrome-config
              mountPath: /config/navidrome.toml
              subPath: navidrome.toml
          # Resource requests and limits
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Probes for health checks
          livenessProbe:
            httpGet:
              path: /ping
              port: 4533
            initialDelaySeconds: 30
            periodSeconds: 10
          # Probe to check if the application is ready to serve traffic
          readinessProbe:
            httpGet:
              path: /ping
              port: 4533
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-auto
        - name: navidrome-config
          configMap:
            name: navidrome-config
            items:
              - key: navidrome.toml
                path: navidrome.toml
