# Navidrome Deployment manifest for Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          ports:
            - containerPort: 4533
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            # Mount config directory
            - name: media-storage
              mountPath: /config
              subPath: navidrome/config
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-auto
        - name: navidrome-config
          configMap:
            name: navidrome-config
            items:
              - key: navidrome.toml
                path: navidrome.toml
