# Lidaar Service Manifest for Kubernetes
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  type: NodePort
  selector:
    app: lidarr
  ports:
    - name: http
      port: 8686 # Internal cluster port
      targetPort: 8686 # Container port
      nodePort: 30086 # External access port
    - name: https
      port: 8687 # Internal cluster port
      targetPort: 8687 # Container port
      nodePort: 30087 # External access port
    - name: lidarr-api
      port: 8688 # Internal cluster port
      targetPort: 8688 # Container port
      nodePort: 30088 # External access port
