apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  type: NodePort
  selector:
    app: lidarr
  ports:
    - name: http
      port: 8686 # Internal cluster port
      targetPort: 8686 # Container port
      nodePort: 30086 # External access port
