apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media
spec:
  type: NodePort
  selector:
    app: slskd
  ports:
    - name: http
      port: 5030
      targetPort: 5030
      nodePort: 30030
    - name: https
      port: 5031
      targetPort: 5031
      nodePort: 30031
    - name: soulseek
      port: 50300
      targetPort: 50300
      nodePort: 30300 # External port for peer connections

