apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      nodePort: 30080 # Forward router port 80 to this
    - name: websecure
      port: 443
      nodePort: 30443 # Forward router port 443 to this
    - name: dashboard
      port: 8080
      nodePort: 30090

