apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-config
  namespace: media
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>9696</Port>
      <SslPort>6969</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <AuthenticationMethod>Forms</AuthenticationMethod>
      <AuthenticationRequired>Enabled</AuthenticationRequired>
      <Username>admin</Username>  <!-- TODO: Change this -->
      <Password>admin</Password>  <!-- TODO: Change this -->
      <ApiKey>/3Bmu6ILs45HJIDdK+nN2N+kZwbrsqI8+Ug93DioXmuVny2koipLtK6wvDRqUhGL</ApiKey>
      <Branch>master</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Prowlarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
    </Config>

