apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    # Namespace identification for network policies
    name: media
    # Pod Security Standards enforcement
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

